---
review:
  conferences:
    - { name: "IEEE International Conference on Computer Communications (INFOCOM)", year: [2023, 2024, 2025] }
    - { name: "ACM Conference on Embedded Networked Sensor Systems (Sensys)", year: [2024] }
    - { name: "IEEE International Conference on Communications - Next-Generation Networking & Internet (ICC)", year: [2022, 2023] }
  journals:
    - { name: "IEEE Transactions on Consumer Electronics (TCE)", year: [2025] }
    - { name: "IEEE Transactions on Dependable and Secure Computing (TDSC)", year: [2025] }
    - { name: "IEEE Transaction on Mobile Computing (TMC)", year: [2023, 2024] }
    - { name: "IEEE Internet of Things Journal (JIOT)", year: [2022] }
    - { name: "IEEE Transaction on Vehicular Technology (TVT)", year: [2022] }

teaching:
  ta:
    - { course: "CDA 3100: Computer Organization", place: "FSU", duration: "Fall 2022, Spring 2024, Spring/Fall 2025" }
    - { course: "COP 4521: Secure, Parallel, Distributed programming ", place: "FSU", duration: "Fall 2023" }
    - { course: "CEN 4090: Software Engineering Capstone ", place: "FSU", duration: "Fall 2023" }
  research_tutor:
    - { role: "Undergraduate Student Research Internship",  duration: "Fall 2024 - present", student: "Carson Rivera", project: Medical chatbox for weight losing and Speculative decoding for efficient collaborative LLM}
    - { role: "Young Scholars Program for high school students",  duration: "Summer 2023", student: "Rohil Agarwal, Mathew Cai", project: Personalized federated learning for high school quality rating }
    - { role: "Undergraduate Student Research Internship",  duration: "Fall 2022 - Spring 2023", student: "Gabriel Mourad, Daniel Gandelman", project: Federated learning with local differential privacy and Fair resource allocation }

invited_presentations:
  - { name: "Student seminar at FSU Compute Science", place: "FSU", year: 2024.11 }

---
(Optional notes)